site_name: MiRco documentation
nav:
  - Documentation overview: index.md
  - Installation: installation.md
  - File structure: file_structure.md
  - MiRco:
    - Overview: MiRco/mirco_overview.md
    - MiRco interface: MiRco/mirco_interface.md
    - Starting MiRco: MiRco/mirco_start.md
    - Connect to MiRco: MiRco/mirco_connection.md
    - Industrial control: MiRco/mirco_industrial_control.md
    - ROS control: MiRco/mirco_ros_control.md
  - MiR100:
    - Overview: MiR100/mir_overview.md
    - Starting MiR100: MiR100/mir_start.md
    - Connect to MiR100: MiR100/mir_connection.md
    - Web interface: MiR100/mir_web_interface.md
    - ROS control: MiR100/mir_ros_control.md
    - REST API: MiR100/mir_rest_api.md
    # - Glossary: MiR100/mir_glossary.md
  - UR5e & Robotiq 2F-85:
    - Overview: UR5e_2F85/ur_2f85_overview.md
    - Starting UR5e & Robotiq 2F-85: UR5e_2F85/ur_2f85_start.md
    - ROS control: UR5e_2F85/ur_2f85_ros_control.md
theme:
  name: material
  logo: img/robolab_crop.png
  palette:
    primary: black
  features:
    - navigation.path
    - navigation.sections
    - navigation.footer
    # - navigation.tabs
    # - navigation.tabs.sticky
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 3
extra_css: 
  - stylesheets/extra.css
plugins:
  - search
  - mkdocstrings:
      enabled: true
      handlers:
          python:
            paths: [docs/MiR100/mir_rest_api]
            options:
              docstring_style: sphinx
  - print-site:
      enabled: true
      print_page_title: 'MiRco documentation'
      add_table_of_contents: false
      enumerate_headings: false